window.SiteData = {
  nav: [
    ["Home", "index.html", "home"],
    ["About", "about.html", "about"],
    ["Services", "services.html", "services"],
    ["Products", "products.html", "products"],
    ["Projects", "projects.html", "projects"],
    ["Blogs", "blogs.html", "blogs"],
    ["Contact", "contact.html", "contact"]
  ],
  stats: [
    ["20+", "Years Experience"],
    ["50+", "Countries"],
    ["500+", "Products"],
    ["1000+", "Clients"]
  ],
  services: [
    {
      title: "Export Consultation",
      slug: "export-consultation",
      image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=900&q=80",
      text: "Market entry planning, buyer readiness, compliance routes, and practical export strategy.",
      benefits: ["Market validation", "Buyer documentation", "Compliance roadmap"],
      process: ["Assess requirement", "Map destination rules", "Prepare export plan"]
    },
    {
      title: "Product Sourcing",
      slug: "product-sourcing",
      image: "https://images.unsplash.com/photo-1578575437130-527eed3abbec?auto=format&fit=crop&w=900&q=80",
      text: "Verified supplier networks and quality-led procurement for agricultural and industrial categories.",
      benefits: ["Vetted vendors", "Sample coordination", "Transparent origin"],
      process: ["Define specs", "Shortlist producers", "Approve sample"]
    },
    {
      title: "Documentation",
      slug: "documentation",
      image: "https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?auto=format&fit=crop&w=900&q=80",
      text: "Commercial invoices, packing lists, COO, phytosanitary support, and shipment records.",
      benefits: ["Accurate paperwork", "Fewer delays", "Audit-ready records"],
      process: ["Collect shipment data", "Prepare documents", "Final compliance check"]
    },
    {
      title: "Packaging",
      slug: "packaging",
      image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=900&q=80",
      text: "Retail, bulk, and private-label packaging designed for safe international movement.",
      benefits: ["Custom labels", "Transit protection", "Export-grade materials"],
      process: ["Select format", "Approve artwork", "Pack and seal"]
    },
    {
      title: "Freight Forwarding",
      slug: "freight-forwarding",
      image: "https://images.unsplash.com/photo-1494412519320-aa613dfb7738?auto=format&fit=crop&w=900&q=80",
      text: "Air, sea, and multimodal freight planning with dependable carrier coordination.",
      benefits: ["Carrier options", "Route optimization", "Shipment tracking"],
      process: ["Compare routes", "Book freight", "Monitor movement"]
    },
    {
      title: "Warehousing",
      slug: "warehousing",
      image: "https://images.unsplash.com/photo-1587293852726-70cdb56c2866?auto=format&fit=crop&w=900&q=80",
      text: "Inventory staging, consolidation, and dispatch readiness for multi-SKU export programs.",
      benefits: ["Consolidation", "Inventory control", "Dispatch planning"],
      process: ["Receive goods", "Inspect lots", "Prepare dispatch"]
    },
    {
      title: "Customs Clearance",
      slug: "customs-clearance",
      image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=900&q=80",
      text: "Customs partner coordination to keep exports moving cleanly across borders.",
      benefits: ["HS guidance", "Broker coordination", "Reduced clearance risk"],
      process: ["Classify goods", "File documents", "Clear shipment"]
    },
    {
      title: "Door-to-Door Delivery",
      slug: "door-to-door-delivery",
      image: "https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?auto=format&fit=crop&w=900&q=80",
      text: "Complete movement from origin facility to buyer destination with single-window updates.",
      benefits: ["One contact", "End-to-end tracking", "Final-mile support"],
      process: ["Plan route", "Move shipment", "Confirm delivery"]
    }
  ],
  products: [
    {
      name: "Premium Green Cardamom",
      slug: "premium-green-cardamom",
      category: "Spices",
      country: "India",
      industry: "Food",
      availability: "In Stock",
      moq: "500 kg",
      image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=900&q=80",
      description: "Bold aroma, export-cleaned pods for premium retail and foodservice blends.",
      specs: ["Moisture below 12%", "Machine cleaned", "Whole pod grading"],
      packaging: "10 kg vacuum bags in master cartons",
      shipping: "Sea and air freight available",
      certifications: "FSSAI, APEDA, ISO-ready lots"
    },
    {
      name: "Organic Turmeric Fingers",
      slug: "organic-turmeric-fingers",
      category: "Spices",
      country: "India",
      industry: "Food",
      availability: "Seasonal",
      moq: "1 MT",
      image: "https://images.unsplash.com/photo-1615485500704-8e990f9900f7?auto=format&fit=crop&w=900&q=80",
      description: "Naturally cured turmeric fingers with vivid color and consistent curcumin profile.",
      specs: ["Polished or unpolished", "Curcumin 3%+", "Low foreign matter"],
      packaging: "25 kg PP bags with liner",
      shipping: "FCL and LCL shipping",
      certifications: "Organic lots on request"
    },
    {
      name: "Basmati Rice 1121",
      slug: "basmati-rice-1121",
      category: "Grains",
      country: "India",
      industry: "Retail",
      availability: "In Stock",
      moq: "5 MT",
      image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=900&q=80",
      description: "Long-grain aromatic basmati for importers, supermarkets, and food distributors.",
      specs: ["Aged crop options", "Sortex cleaned", "Broken below buyer spec"],
      packaging: "1 kg to 50 kg private-label bags",
      shipping: "20 ft and 40 ft containers",
      certifications: "ISO, HACCP-ready supply"
    },
    {
      name: "Coconut Coir Blocks",
      slug: "coconut-coir-blocks",
      category: "Agri Inputs",
      country: "Sri Lanka",
      industry: "Agriculture",
      availability: "In Stock",
      moq: "1 x 20 ft",
      image: "https://images.unsplash.com/photo-1598514983318-2f64f8f4796c?auto=format&fit=crop&w=900&q=80",
      description: "Compressed coir substrate blocks for nurseries, hydroponics, and greenhouse farms.",
      specs: ["Low EC", "Washed options", "5 kg blocks"],
      packaging: "Palletized and container loaded",
      shipping: "Containerized sea freight",
      certifications: "Phytosanitary support"
    },
    {
      name: "Mango Pulp Aseptic",
      slug: "mango-pulp-aseptic",
      category: "Processed Food",
      country: "India",
      industry: "Beverage",
      availability: "Pre-order",
      moq: "1 MT",
      image: "https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&w=900&q=80",
      description: "Aseptic mango pulp for juice, dairy, bakery, and dessert manufacturing.",
      specs: ["Alphonso and Totapuri", "Brix aligned", "Aseptic processed"],
      packaging: "215 kg aseptic drums",
      shipping: "Ambient container movement",
      certifications: "HACCP, ISO, FSSAI"
    },
    {
      name: "Cotton Tote Bags",
      slug: "cotton-tote-bags",
      category: "Textiles",
      country: "India",
      industry: "Lifestyle",
      availability: "In Stock",
      moq: "2000 pcs",
      image: "https://images.unsplash.com/photo-1597484662317-9bd7bdda2907?auto=format&fit=crop&w=900&q=80",
      description: "Reusable cotton bags with private-label printing and export-ready finishing.",
      specs: ["Canvas GSM options", "Screen print", "Custom handles"],
      packaging: "Bulk cartons or retail packs",
      shipping: "Air and sea freight",
      certifications: "GOTS options available"
    },
    {
      name: "Whole Black Pepper",
      slug: "whole-black-pepper",
      category: "Spices",
      country: "India",
      industry: "Food",
      availability: "In Stock",
      moq: "500 kg",
      image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=900&q=80",
      description: "Sun-dried whole peppercorns with strong heat and clean export grading.",
      specs: ["Bold grade options", "Low moisture", "Machine cleaned"],
      packaging: "25 kg PP bags with liner",
      shipping: "LCL and FCL sea freight",
      certifications: "FSSAI, APEDA"
    },
    {
      name: "Red Chilli Powder",
      slug: "red-chilli-powder",
      category: "Spices",
      country: "India",
      industry: "Food",
      availability: "In Stock",
      moq: "1 MT",
      image: "https://images.unsplash.com/photo-1588252303782-cb80119abd6d?auto=format&fit=crop&w=900&q=80",
      description: "Vivid chilli powder for processors, distributors, and private-label spice brands.",
      specs: ["Color value aligned", "Fine mesh options", "Batch sampling"],
      packaging: "10 kg and 25 kg export cartons",
      shipping: "Sea and air freight available",
      certifications: "FSSAI, ISO-ready lots"
    },
    {
      name: "Cumin Seeds",
      slug: "cumin-seeds",
      category: "Spices",
      country: "India",
      industry: "Food",
      availability: "Seasonal",
      moq: "750 kg",
      image: "https://images.unsplash.com/photo-1609842947419-ba4f04d5d60f?auto=format&fit=crop&w=900&q=80",
      description: "Aromatic cumin seeds sorted for spice packing and food manufacturing.",
      specs: ["Machine cleaned", "Whole seed supply", "Purity by buyer spec"],
      packaging: "25 kg woven bags",
      shipping: "FCL and LCL shipping",
      certifications: "APEDA support"
    },
    {
      name: "Arabica Coffee Beans",
      slug: "arabica-coffee-beans",
      category: "Beverages",
      country: "India",
      industry: "Foodservice",
      availability: "Pre-order",
      moq: "1 MT",
      image: "https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=900&q=80",
      description: "Roaster-ready arabica beans with origin traceability and lot samples.",
      specs: ["Washed and natural options", "Screen size choices", "Sample approval"],
      packaging: "60 kg jute bags with liner",
      shipping: "Containerized sea freight",
      certifications: "Organic lots on request"
    },
    {
      name: "Orthodox Black Tea",
      slug: "orthodox-black-tea",
      category: "Beverages",
      country: "India",
      industry: "Retail",
      availability: "In Stock",
      moq: "500 kg",
      image: "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?auto=format&fit=crop&w=900&q=80",
      description: "Leaf tea for premium blends, retail packs, and hospitality buyers.",
      specs: ["Leaf grade options", "Estate sourcing", "Blend support"],
      packaging: "Vacuum packs in master cartons",
      shipping: "Air and sea freight",
      certifications: "FSSAI, export documentation"
    },
    {
      name: "Raw Cashew Kernels",
      slug: "raw-cashew-kernels",
      category: "Nuts",
      country: "India",
      industry: "Food",
      availability: "In Stock",
      moq: "500 kg",
      image: "https://images.unsplash.com/photo-1509912760195-4f6cfd8cce2c?auto=format&fit=crop&w=900&q=80",
      description: "Whole and split cashew kernels for snack brands, bakeries, and distributors.",
      specs: ["W320 and W240 options", "Vacuum packed", "Low broken percentage"],
      packaging: "10 kg tins in cartons",
      shipping: "Reefer optional by destination",
      certifications: "HACCP-ready supply"
    },
    {
      name: "Natural Sesame Seeds",
      slug: "natural-sesame-seeds",
      category: "Oilseeds",
      country: "India",
      industry: "Food",
      availability: "Seasonal",
      moq: "1 MT",
      image: "https://images.unsplash.com/photo-1615485500704-8e990f9900f7?auto=format&fit=crop&w=900&q=80",
      description: "Cleaned sesame seeds for bakery, tahini, and food ingredient buyers.",
      specs: ["Natural and hulled options", "Sortex cleaned", "Oil content by lot"],
      packaging: "25 kg paper or PP bags",
      shipping: "Sea freight available",
      certifications: "Phytosanitary support"
    },
    {
      name: "Dehydrated Onion Flakes",
      slug: "dehydrated-onion-flakes",
      category: "Processed Food",
      country: "India",
      industry: "Foodservice",
      availability: "In Stock",
      moq: "1 MT",
      image: "https://images.unsplash.com/photo-1508747703725-719777637510?auto=format&fit=crop&w=900&q=80",
      description: "Crisp dehydrated onion flakes for seasoning, soups, sauces, and ready meals.",
      specs: ["White and red onion options", "Low moisture", "Granule sizes available"],
      packaging: "20 kg cartons with liner",
      shipping: "Ambient container movement",
      certifications: "FSSAI, ISO-ready lots"
    },
    {
      name: "Freeze Dried Banana",
      slug: "freeze-dried-banana",
      category: "Processed Food",
      country: "India",
      industry: "Retail",
      availability: "Pre-order",
      moq: "300 kg",
      image: "https://images.unsplash.com/photo-1528825871115-3581a5387919?auto=format&fit=crop&w=900&q=80",
      description: "Lightweight banana slices for cereal mixes, snacks, and health food packs.",
      specs: ["Crisp texture", "No added sugar options", "Retail pack support"],
      packaging: "Nitrogen flushed pouches in cartons",
      shipping: "Air and sea freight",
      certifications: "HACCP support"
    },
    {
      name: "Organic Jaggery Blocks",
      slug: "organic-jaggery-blocks",
      category: "Sweeteners",
      country: "India",
      industry: "Retail",
      availability: "In Stock",
      moq: "1 MT",
      image: "https://images.unsplash.com/photo-1609501676725-7186f017a4b7?auto=format&fit=crop&w=900&q=80",
      description: "Traditional cane jaggery blocks for ethnic retail and natural sweetener programs.",
      specs: ["Block and powder options", "Natural cane source", "Buyer label support"],
      packaging: "500 g to 25 kg packs",
      shipping: "Ambient sea freight",
      certifications: "Organic lots on request"
    },
    {
      name: "Virgin Coconut Oil",
      slug: "virgin-coconut-oil",
      category: "Oils",
      country: "Sri Lanka",
      industry: "Wellness",
      availability: "In Stock",
      moq: "1 MT",
      image: "https://images.unsplash.com/photo-1598514983318-2f64f8f4796c?auto=format&fit=crop&w=900&q=80",
      description: "Cold-processed coconut oil for food, wellness, and personal care buyers.",
      specs: ["Cold pressed", "Bulk and retail options", "Low moisture"],
      packaging: "Drums, jars, or private-label bottles",
      shipping: "Sea freight and palletized air cargo",
      certifications: "COA and origin documents"
    },
    {
      name: "Handloom Cotton Scarves",
      slug: "handloom-cotton-scarves",
      category: "Textiles",
      country: "India",
      industry: "Lifestyle",
      availability: "Pre-order",
      moq: "1000 pcs",
      image: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=900&q=80",
      description: "Soft cotton scarves with custom colors for boutiques and lifestyle retailers.",
      specs: ["Custom colors", "Size variations", "Brand label support"],
      packaging: "Individual polybags or retail sleeves",
      shipping: "Air and sea freight",
      certifications: "GOTS options available"
    },
    {
      name: "Jute Shopping Bags",
      slug: "jute-shopping-bags",
      category: "Textiles",
      country: "Bangladesh",
      industry: "Lifestyle",
      availability: "In Stock",
      moq: "1500 pcs",
      image: "https://images.unsplash.com/photo-1597484662317-9bd7bdda2907?auto=format&fit=crop&w=900&q=80",
      description: "Reusable jute bags for promotional campaigns, retail stores, and gifting.",
      specs: ["Print ready", "Handle choices", "Laminated options"],
      packaging: "Bulk export cartons",
      shipping: "Sea freight preferred",
      certifications: "Sustainable material declaration"
    },
    {
      name: "Areca Leaf Plates",
      slug: "areca-leaf-plates",
      category: "Eco Products",
      country: "India",
      industry: "Hospitality",
      availability: "In Stock",
      moq: "50000 pcs",
      image: "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=900&q=80",
      description: "Compostable tableware for events, restaurants, and sustainable foodservice programs.",
      specs: ["Multiple shapes", "Heat pressed", "Bulk carton supply"],
      packaging: "Shrink packs in master cartons",
      shipping: "Containerized sea freight",
      certifications: "Compostable declaration available"
    }
  ],
  projects: [
    {
      title: "Spice Consolidation Program",
      country: "UAE",
      products: "Cardamom, turmeric, cumin",
      industry: "Food distribution",
      duration: "9 months",
      image: "https://images.unsplash.com/photo-1578575437130-527eed3abbec?auto=format&fit=crop&w=900&q=80",
      story: "Built a monthly mixed-container program with stronger inspection checkpoints and stable dispatch windows."
    },
    {
      title: "Private Label Rice Launch",
      country: "Saudi Arabia",
      products: "Basmati rice",
      industry: "Retail",
      duration: "6 months",
      image: "https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?auto=format&fit=crop&w=900&q=80",
      story: "Delivered custom packaging, barcode-ready cartons, and repeat container planning for a retail chain."
    },
    {
      title: "Greenhouse Substrate Supply",
      country: "Netherlands",
      products: "Coconut coir blocks",
      industry: "Agriculture",
      duration: "12 months",
      image: "https://images.unsplash.com/photo-1592982537447-7440770cbfc9?auto=format&fit=crop&w=900&q=80",
      story: "Coordinated quality lots, phytosanitary documentation, and container loading for horticulture buyers."
    }
  ],
  blogs: [
    {
      title: "How Export Buyers Evaluate Supplier Reliability",
      slug: "buyer-supplier-reliability",
      category: "Sourcing",
      read: "6 min read",
      tags: ["Sourcing", "Quality", "B2B"],
      image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=900&q=80",
      excerpt: "A practical framework for documentation, sampling, communication, and repeat order confidence.",
      body: "Reliable export supply starts before the shipment. Buyers look for clear specifications, responsive communication, consistent sampling, traceable origin, and document discipline. The best exporters reduce ambiguity at every stage, from quotation to dispatch."
    },
    {
      title: "Packaging Decisions That Reduce Freight Risk",
      slug: "packaging-freight-risk",
      category: "Logistics",
      read: "5 min read",
      tags: ["Packaging", "Freight", "Quality"],
      image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=900&q=80",
      excerpt: "The packaging choices that protect product quality through long international routes.",
      body: "Export packaging must match climate, route, handling, and shelf expectations. Strong cartons, liners, palletization, container planning, and label accuracy all help shipments arrive in saleable condition."
    },
    {
      title: "Why Country-of-Origin Transparency Matters",
      slug: "origin-transparency",
      category: "Compliance",
      read: "4 min read",
      tags: ["Origin", "Compliance", "Trust"],
      image: "https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?auto=format&fit=crop&w=900&q=80",
      excerpt: "Origin clarity supports compliance, brand trust, and stronger long-term buyer relationships.",
      body: "Country-of-origin details affect duties, product claims, retailer requirements, and customer trust. Exporters should maintain traceability across suppliers, production batches, and shipment records."
    }
  ],
  countries: [
    ["UAE", "Spices, rice, textiles", "8 years", "68%", "47%"],
    ["Netherlands", "Coir, processed food", "5 years", "47%", "38%"],
    ["Saudi Arabia", "Rice, spices", "11 years", "59%", "51%"],
    ["USA", "Organic foods, textiles", "6 years", "24%", "43%"],
    ["Australia", "Agri inputs, spices", "4 years", "82%", "68%"]
  ],
  testimonials: [
    ["A polished partner with disciplined paperwork, consistent shipment updates, and the kind of calm communication our procurement team needs when containers are moving across time zones. Their team keeps every stage visible, from quote confirmation to document review and final dispatch.", "Procurement Director, UAE"],
    ["Their packaging support helped us launch a retail-ready rice line faster. The cartons, labels, and dispatch planning were handled with practical detail from sample approval to final loading, and our internal team could approve every change without delay.", "Category Manager, Saudi Arabia"],
    ["Quality checks were clear, photographed, and easy to approve remotely. We always knew what was ready, what was pending, and what documents were coming next, which made the import process easier for our warehouse and compliance teams.", "Importer, Netherlands"],
    ["Spicyva made mixed spice consolidation feel simple. MOQ planning, product photos, invoice drafts, and shipping options were all shared in a buyer-friendly way, so our team could compare lots and commit with confidence.", "Food Distributor, Qatar"],
    ["The team understands that export work is not only about price. Their timing, document accuracy, and quick replies helped us build a repeat supply program with fewer surprises and a much smoother handoff to our freight partners.", "Operations Lead, Australia"],
    ["We needed a supplier who could support private-label packaging without slowing down the shipment. Their coordination between sourcing, packing, and freight was dependable, and they gave us enough detail to keep our retail launch on schedule.", "Retail Buyer, USA"]
  ]
};
