window.Screens = window.Screens || {};

window.Screens.contactFull = function () {
  return (
    '<section class="section contact-section"><div class="shell contact-layout">' +
    '<form class="contact-form-card fade-in" id="contactForm"><div><p class="eyebrow">Inquiry Form</p><h2 class="section-title">Tell us what you want to export or source.</h2><p class="section-lead">Share product, quantity, destination, packaging, and document needs. We reply with a clear next step.</p></div><div class="form-grid"><label><span>Full name</span><input class="field" placeholder="Your name"></label><label><span>Company</span><input class="field" placeholder="Company name"></label><label><span>Email</span><input class="field" placeholder="name@example.com"></label><label><span>Phone / WhatsApp</span><input class="field" placeholder="+91"></label><label><span>Request type</span><select class="field"><option>Request quotation</option><option>Product sourcing</option><option>Documentation support</option><option>Partnership</option></select></label><label><span>Destination</span><input class="field" placeholder="Destination country"></label></div><label class="full-field"><span>Requirement</span><textarea class="field" placeholder="Product, quantity, packaging, certification, and expected timeline"></textarea></label><button class="btn" type="button">Submit Inquiry</button></form>' +
    '<aside class="contact-info-panel fade-in"><p class="eyebrow">Trade Desk</p><h3>Direct support for serious inquiries.</h3><p>Speak with our export desk for product availability, sample movement, packing guidance, freight options, and document coordination.</p><div class="contact-info-list"><span><strong>Location</strong> Chennai, Tamil Nadu, India</span><span><strong>Phone</strong> +91 98765 43210</span><span><strong>Email</strong> sales@spicyvaexports.com</span><span><strong>Hours</strong> Mon-Sat, 9:30 AM - 6:30 PM</span></div><div class="btn-row"><a class="btn gold" href="https://wa.me/919876543210">WhatsApp</a><a class="btn secondary" href="mailto:sales@spicyvaexports.com">Email Us</a></div></aside>' +
    '</div></section><section class="section alt contact-faq-section"><div class="shell grid three">' +
    ["How soon do you quote?", "Can you arrange samples?", "Do you support custom packaging?"].map(function (q) { return '<article class="card pad fade-in"><h3>' + q + '</h3><p>Yes. Our team reviews destination, quantity, product specifications, packing needs, and document requirements before confirming a practical next step.</p></article>'; }).join("") +
    "</div></section>"
  );
};
